#!/usr/bin/env python3
"""Native ComfyUI-BrushNet adapter for PowerPaint v2.1 object removal.

This backend is deliberately narrow. It sits behind the Asset Studio's already-
approved automatic mask stack and only answers the question: can a task-conditioned
PowerPaint object-removal model execute a physical removal more reliably than
blind context completion?

The graph follows the pinned ComfyUI-BrushNet PowerPaint object-removal example:
- SD1.5 base checkpoint supplies MODEL/CLIP/VAE;
- PowerPaint v2.1 BrushNet is loaded through BrushNetLoader;
- the learned PowerPaint text encoder is loaded through PowerPaintCLIPLoader;
- standard positive/negative conditioning is encoded with the base checkpoint CLIP;
- PowerPaint(function='object removal') injects P_ctxt/P_obj task conditioning;
- KSampler uses Euler/normal with caller-controlled steps/CFG/seed;
- VAEDecode + SaveImage produce the candidate crop.

The user never draws a mask. The mask is generated by the proven Runner66 pipeline.
"""

from __future__ import annotations

import shutil
import time
from pathlib import Path
from typing import Any

from PIL import Image

from adapter_protocol import GenerationResult, StaticGenerationRequest
from flux2_klein_adapter import Flux2KleinAdapter, sha256_file

BASE_CHECKPOINT = "v1-5-pruned-emaonly.safetensors"
BASE_CHECKPOINT_SHA256 = "6ce0161689b3853acaa03779ec93eafe75a02f4ced659bee03f50797806fa2fa"
POWERPAINT_BRUSHNET = "powerpaint/diffusion_pytorch_model.safetensors"
POWERPAINT_BRUSHNET_SHA256 = "530f2886ef5bcdf199269ec344155a517639ba64219b85eeb23fd86aab93147f"
POWERPAINT_TEXT_ENCODER = "powerpaint/pytorch_model.bin"
POWERPAINT_TEXT_ENCODER_SHA256 = "73709b4360ca06ef990a67d090e8d81a4310943d67a88845653fc4e9f7f26b65"
BASE_CLIP = "model.fp16.safetensors"
BASE_CLIP_SHA256 = "77795e2023adcf39bc29a884661950380bd093cf0750a966d473d1718dc9ef4e"

REQUIRED_NODES = (
    "CheckpointLoaderSimple",
    "BrushNetLoader",
    "PowerPaintCLIPLoader",
    "LoadImage",
    "ImageToMask",
    "CLIPTextEncode",
    "PowerPaint",
    "KSampler",
    "VAEDecode",
    "SaveImage",
)


class PowerPaintBrushNetAdapter(Flux2KleinAdapter):
    adapter_id = "powerpaint_v2_1_brushnet_object_removal"

    @staticmethod
    def _normalized_dropdown_path(value: str) -> str:
        return str(value).replace("\\", "/")

    def _resolve_dropdown_value(self, node_name: str, input_name: str, preferred: str) -> str:
        """Return the exact dropdown value advertised by ComfyUI.

        ComfyUI custom nodes often expose relative model paths using the host OS
        separator. Asset Studio stores canonical model ids with forward slashes.
        Compare normalized forms, but send the exact runtime-advertised string back
        in the prompt so validation is platform-independent.
        """
        info = self._request_json(self.base_url + f"/object_info/{node_name}", timeout=30)
        try:
            spec = info[node_name]["input"]["required"][input_name]
            choices = spec[0]
        except (KeyError, IndexError, TypeError) as exc:
            raise RuntimeError(
                f"could not inspect dropdown {node_name}.{input_name}: {info}"
            ) from exc
        if not isinstance(choices, list):
            raise RuntimeError(
                f"ComfyUI dropdown {node_name}.{input_name} did not expose a choice list: {choices!r}"
            )
        wanted = self._normalized_dropdown_path(preferred)
        for choice in choices:
            if self._normalized_dropdown_path(str(choice)) == wanted:
                return str(choice)
        raise RuntimeError(
            f"required model option {preferred!r} not advertised by {node_name}.{input_name}; "
            f"available={choices!r}"
        )

    def verify_runtime(self) -> None:
        if self._verified:
            return
        self._request_json(self.base_url + "/system_stats", timeout=15)
        self._verify_file(
            self.comfy_root / "models" / "checkpoints" / BASE_CHECKPOINT,
            BASE_CHECKPOINT_SHA256,
            BASE_CHECKPOINT,
        )
        self._verify_file(
            self.comfy_root / "models" / "inpaint" / "powerpaint" / "diffusion_pytorch_model.safetensors",
            POWERPAINT_BRUSHNET_SHA256,
            POWERPAINT_BRUSHNET,
        )
        self._verify_file(
            self.comfy_root / "models" / "inpaint" / "powerpaint" / "pytorch_model.bin",
            POWERPAINT_TEXT_ENCODER_SHA256,
            POWERPAINT_TEXT_ENCODER,
        )
        self._verify_file(
            self.comfy_root / "models" / "clip" / BASE_CLIP,
            BASE_CLIP_SHA256,
            BASE_CLIP,
        )
        for node_name in REQUIRED_NODES:
            info = self._request_json(self.base_url + f"/object_info/{node_name}", timeout=30)
            if node_name not in info:
                raise RuntimeError(f"required ComfyUI-BrushNet node unavailable: {node_name}")

        # Model dropdowns are host-path-sensitive. Resolve the exact strings that
        # this ComfyUI instance advertises instead of assuming POSIX separators.
        self._brushnet_dropdown = self._resolve_dropdown_value(
            "BrushNetLoader", "brushnet", POWERPAINT_BRUSHNET
        )
        self._powerpaint_text_dropdown = self._resolve_dropdown_value(
            "PowerPaintCLIPLoader", "powerpaint", POWERPAINT_TEXT_ENCODER
        )
        self._base_clip_dropdown = self._resolve_dropdown_value(
            "PowerPaintCLIPLoader", "base", BASE_CLIP
        )
        self._verified = True

    def _prepare_native_file(self, source: Path, job_id: str, filename: str, mask: bool = False) -> tuple[str, str]:
        source = Path(source).resolve()
        if not source.is_file():
            raise FileNotFoundError(source)
        target_dir = self.comfy_root / "input" / "roguelite_asset_studio" / job_id
        target_dir.mkdir(parents=True, exist_ok=True)
        target = target_dir / filename
        with Image.open(source) as opened:
            opened.load()
            if mask:
                gray = opened.convert("L")
                Image.merge("RGB", (gray, gray, gray)).save(target, format="PNG")
            elif "A" in opened.getbands():
                rgba = opened.convert("RGBA")
                background = Image.new("RGBA", rgba.size, (128, 128, 128, 255))
                background.alpha_composite(rgba)
                background.convert("RGB").save(target, format="PNG")
            else:
                opened.convert("RGB").save(target, format="PNG")
        relative = target.relative_to(self.comfy_root / "input").as_posix()
        return relative, sha256_file(source)

    @staticmethod
    def _next_id(counter: list[int]) -> str:
        value = str(counter[0])
        counter[0] += 1
        return value

    def _build_prompt(
        self,
        request: StaticGenerationRequest,
        source_name: str,
        mask_name: str,
        output_prefix: str,
    ) -> dict[str, Any]:
        counter = [1]
        graph: dict[str, Any] = {}

        base_id = self._next_id(counter)
        graph[base_id] = {
            "inputs": {"ckpt_name": BASE_CHECKPOINT},
            "class_type": "CheckpointLoaderSimple",
        }
        brush_id = self._next_id(counter)
        graph[brush_id] = {
            "inputs": {"brushnet": self._brushnet_dropdown, "dtype": "float16"},
            "class_type": "BrushNetLoader",
        }
        ppclip_id = self._next_id(counter)
        graph[ppclip_id] = {
            "inputs": {
                "base": self._base_clip_dropdown,
                "powerpaint": self._powerpaint_text_dropdown,
            },
            "class_type": "PowerPaintCLIPLoader",
        }
        source_id = self._next_id(counter)
        graph[source_id] = {"inputs": {"image": source_name}, "class_type": "LoadImage"}
        mask_load_id = self._next_id(counter)
        graph[mask_load_id] = {"inputs": {"image": mask_name}, "class_type": "LoadImage"}
        mask_id = self._next_id(counter)
        graph[mask_id] = {
            "inputs": {"image": [mask_load_id, 0], "channel": "red"},
            "class_type": "ImageToMask",
        }
        pos_id = self._next_id(counter)
        graph[pos_id] = {
            "inputs": {"text": request.prompt, "clip": [base_id, 1]},
            "class_type": "CLIPTextEncode",
        }
        neg_id = self._next_id(counter)
        graph[neg_id] = {
            "inputs": {"text": request.negative or "", "clip": [base_id, 1]},
            "class_type": "CLIPTextEncode",
        }
        powerpaint_id = self._next_id(counter)
        graph[powerpaint_id] = {
            "inputs": {
                "model": [base_id, 0],
                "vae": [base_id, 2],
                "image": [source_id, 0],
                "mask": [mask_id, 0],
                "powerpaint": [brush_id, 0],
                "clip": [ppclip_id, 0],
                "positive": [pos_id, 0],
                "negative": [neg_id, 0],
                "fitting": 1.0,
                "function": "object removal",
                "scale": 1.0,
                "start_at": 0,
                "end_at": 10000,
                "save_memory": "max",
            },
            "class_type": "PowerPaint",
        }
        sampler_id = self._next_id(counter)
        graph[sampler_id] = {
            "inputs": {
                "seed": int(request.seed),
                "steps": int(request.steps),
                "cfg": float(request.cfg),
                "sampler_name": request.sampler,
                "scheduler": "normal",
                "denoise": 1.0,
                "model": [powerpaint_id, 0],
                "positive": [powerpaint_id, 1],
                "negative": [powerpaint_id, 2],
                "latent_image": [powerpaint_id, 3],
            },
            "class_type": "KSampler",
        }
        decode_id = self._next_id(counter)
        graph[decode_id] = {
            "inputs": {"samples": [sampler_id, 0], "vae": [base_id, 2]},
            "class_type": "VAEDecode",
        }
        save_id = self._next_id(counter)
        graph[save_id] = {
            "inputs": {"filename_prefix": output_prefix, "images": [decode_id, 0]},
            "class_type": "SaveImage",
        }
        return graph

    def generate_masked(
        self,
        request: StaticGenerationRequest,
        automatic_mask: Path,
        destination: Path,
    ) -> GenerationResult:
        request.validate()
        if len(request.references) != 1:
            raise ValueError("PowerPaint object-removal path requires exactly one source-image reference")
        source = Path(request.references[0].path).resolve()
        automatic_mask = Path(automatic_mask).resolve()
        with Image.open(source) as src, Image.open(automatic_mask) as msk:
            if src.size != msk.size:
                raise ValueError(f"source/mask size mismatch: {src.size} vs {msk.size}")
            if src.width % 8 or src.height % 8:
                raise ValueError(f"PowerPaint source size must be divisible by 8: {src.size}")
        self.verify_runtime()

        source_name, source_hash = self._prepare_native_file(source, request.job_id, "source.png", mask=False)
        mask_name, mask_hash = self._prepare_native_file(automatic_mask, request.job_id, "automatic_mask.png", mask=True)
        output_prefix = f"roguelite_asset_studio/{request.job_id}"
        graph = self._build_prompt(request, source_name, mask_name, output_prefix)

        started = time.time()
        submission = self._request_json(self.base_url + "/prompt", {"prompt": graph}, timeout=60)
        prompt_id = submission.get("prompt_id")
        if not prompt_id:
            raise RuntimeError(f"ComfyUI did not return prompt_id: {submission}")
        generated = self._wait_for_output(prompt_id)
        elapsed = time.time() - started

        destination = Path(destination).resolve()
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(generated, destination)
        with Image.open(destination) as image:
            image.load()
            if image.size != (request.width, request.height):
                raise RuntimeError(f"PowerPaint output size {image.size} differs from requested {(request.width, request.height)}")

        return GenerationResult(
            adapter_id=self.adapter_id,
            prompt_id=prompt_id,
            output_path=destination,
            elapsed_seconds=elapsed,
            request=request,
            reference_hashes=(source_hash, mask_hash),
            output_sha256=sha256_file(destination),
        )
