#!/usr/bin/env python3
"""Mask-native sibling adapter for Qwen-Image-Edit-2511.

The user never supplies a production mask manually. The mask is generated by the
Asset Studio perception/structural pipeline and is treated as control data, not
as a semantic image reference.

Key difference from qwen_image_edit_2511_adapter.py:
- Qwen receives only the source crop as visual conditioning;
- a white-on-black automatic mask is scaled through the same
  FluxKontextImageScale path as the source;
- ImageToMask converts that scaled control image into a MASK;
- SetLatentNoiseMask attaches the mask to the source latent before KSampler;
- no red/colored guide image is ever shown to Qwen.
"""

from __future__ import annotations

import shutil
import time
from pathlib import Path
from typing import Any

from PIL import Image

from adapter_protocol import GenerationResult, StaticGenerationRequest
from flux2_klein_adapter import sha256_file
from qwen_image_edit_2511_adapter import (
    QwenImageEdit2511Adapter,
    MODEL,
    TEXT_ENCODER,
    VAE,
)

EXTRA_REQUIRED_NODES = (
    "ImageToMask",
    "SetLatentNoiseMask",
)


class QwenImageEdit2511MaskedAdapter(QwenImageEdit2511Adapter):
    adapter_id = "qwen_image_edit_2511_fp8mixed_masked_latent"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._masked_nodes_verified = False

    def verify_runtime(self) -> None:
        super().verify_runtime()
        if self._masked_nodes_verified:
            return
        for node_name in EXTRA_REQUIRED_NODES:
            info = self._request_json(self.base_url + f"/object_info/{node_name}", timeout=30)
            if node_name not in info:
                raise RuntimeError(f"required native ComfyUI mask node unavailable: {node_name}")
        self._masked_nodes_verified = True

    def _prepare_mask_native(self, source: Path, job_id: str) -> tuple[str, str]:
        source = Path(source).resolve()
        if not source.is_file():
            raise FileNotFoundError(source)
        target_dir = self.comfy_root / "input" / "roguelite_asset_studio" / job_id
        target_dir.mkdir(parents=True, exist_ok=True)
        target = target_dir / "automatic_noise_mask.png"
        with Image.open(source) as opened:
            mask = opened.convert("L")
            rgb = Image.merge("RGB", (mask, mask, mask))
            rgb.save(target, format="PNG")
        relative = target.relative_to(self.comfy_root / "input").as_posix()
        return relative, sha256_file(source)

    @staticmethod
    def _next_id(counter: list[int]) -> str:
        value = str(counter[0])
        counter[0] += 1
        return value

    def _build_masked_prompt(
        self,
        request: StaticGenerationRequest,
        source_name: str,
        mask_name: str,
        output_prefix: str,
    ) -> dict[str, Any]:
        counter = [1]
        graph: dict[str, Any] = {}

        model_id = self._next_id(counter)
        graph[model_id] = {
            "inputs": {"unet_name": MODEL, "weight_dtype": "default"},
            "class_type": "UNETLoader",
        }
        clip_id = self._next_id(counter)
        graph[clip_id] = {
            "inputs": {"clip_name": TEXT_ENCODER, "type": "qwen_image", "device": "cpu"},
            "class_type": "CLIPLoader",
        }
        vae_id = self._next_id(counter)
        graph[vae_id] = {"inputs": {"vae_name": VAE}, "class_type": "VAELoader"}

        source_load_id = self._next_id(counter)
        graph[source_load_id] = {"inputs": {"image": source_name}, "class_type": "LoadImage"}
        source_scale_id = self._next_id(counter)
        graph[source_scale_id] = {
            "inputs": {"image": [source_load_id, 0]},
            "class_type": "FluxKontextImageScale",
        }
        source_latent_id = self._next_id(counter)
        graph[source_latent_id] = {
            "inputs": {"pixels": [source_scale_id, 0], "vae": [vae_id, 0]},
            "class_type": "VAEEncode",
        }

        mask_load_id = self._next_id(counter)
        graph[mask_load_id] = {"inputs": {"image": mask_name}, "class_type": "LoadImage"}
        mask_scale_id = self._next_id(counter)
        graph[mask_scale_id] = {
            "inputs": {"image": [mask_load_id, 0]},
            "class_type": "FluxKontextImageScale",
        }
        mask_extract_id = self._next_id(counter)
        graph[mask_extract_id] = {
            "inputs": {"image": [mask_scale_id, 0], "channel": "red"},
            "class_type": "ImageToMask",
        }
        masked_latent_id = self._next_id(counter)
        graph[masked_latent_id] = {
            "inputs": {"samples": [source_latent_id, 0], "mask": [mask_extract_id, 0]},
            "class_type": "SetLatentNoiseMask",
        }

        def conditioning(text: str) -> str:
            encode_id = self._next_id(counter)
            graph[encode_id] = {
                "inputs": {
                    "clip": [clip_id, 0],
                    "vae": [vae_id, 0],
                    "prompt": text,
                    "image1": [source_scale_id, 0],
                },
                "class_type": "TextEncodeQwenImageEditPlus",
            }
            method_id = self._next_id(counter)
            graph[method_id] = {
                "inputs": {
                    "conditioning": [encode_id, 0],
                    "reference_latents_method": "index_timestep_zero",
                },
                "class_type": "FluxKontextMultiReferenceLatentMethod",
            }
            return method_id

        positive_id = conditioning(request.prompt)
        negative_id = conditioning(request.negative or "")

        sampling_id = self._next_id(counter)
        graph[sampling_id] = {
            "inputs": {"model": [model_id, 0], "shift": 3.1},
            "class_type": "ModelSamplingAuraFlow",
        }
        cfgnorm_id = self._next_id(counter)
        graph[cfgnorm_id] = {
            "inputs": {"model": [sampling_id, 0], "strength": 1.0},
            "class_type": "CFGNorm",
        }
        sampler_id = self._next_id(counter)
        graph[sampler_id] = {
            "inputs": {
                "seed": int(request.seed),
                "steps": int(request.steps),
                "cfg": float(request.cfg),
                "sampler_name": request.sampler,
                "scheduler": "simple",
                "denoise": 1.0,
                "model": [cfgnorm_id, 0],
                "positive": [positive_id, 0],
                "negative": [negative_id, 0],
                "latent_image": [masked_latent_id, 0],
            },
            "class_type": "KSampler",
        }
        decode_id = self._next_id(counter)
        graph[decode_id] = {
            "inputs": {"samples": [sampler_id, 0], "vae": [vae_id, 0]},
            "class_type": "VAEDecode",
        }
        save_id = self._next_id(counter)
        graph[save_id] = {
            "inputs": {"filename_prefix": output_prefix, "images": [decode_id, 0]},
            "class_type": "SaveImage",
        }
        return graph

    def generate_masked(
        self,
        request: StaticGenerationRequest,
        automatic_mask: Path,
        destination: Path,
    ) -> GenerationResult:
        request.validate()
        if len(request.references) != 1:
            raise ValueError("masked Qwen2511 path requires exactly one source-image reference")
        self.verify_runtime()

        source_name, source_hash = self._prepare_reference_native(
            Path(request.references[0].path), request.job_id, 1
        )
        mask_name, mask_hash = self._prepare_mask_native(Path(automatic_mask), request.job_id)

        output_prefix = f"roguelite_asset_studio/{request.job_id}"
        prompt = self._build_masked_prompt(request, source_name, mask_name, output_prefix)
        started = time.time()
        submission = self._request_json(self.base_url + "/prompt", {"prompt": prompt}, timeout=60)
        prompt_id = submission.get("prompt_id")
        if not prompt_id:
            raise RuntimeError(f"ComfyUI did not return prompt_id: {submission}")
        generated = self._wait_for_output(prompt_id)
        elapsed = time.time() - started

        destination = Path(destination).resolve()
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(generated, destination)
        with Image.open(destination) as image:
            image.load()
            if image.width < 16 or image.height < 16:
                raise RuntimeError(f"invalid generated image size: {image.size}")

        return GenerationResult(
            adapter_id=self.adapter_id,
            prompt_id=prompt_id,
            output_path=destination,
            elapsed_seconds=elapsed,
            request=request,
            reference_hashes=(source_hash, mask_hash),
            output_sha256=sha256_file(destination),
        )
